"""
demo/app.py — Deepfake Detection Game (cache-based)

Requires demo/cache/ to be pre-generated by generate_cache.py.
Run: .venv/bin/python demo/app.py  (from project root)
"""

import json
import os
import random
import sys

from flask import Flask, jsonify, render_template, send_from_directory, session

ROOT      = os.path.dirname(os.path.abspath(__file__))
CACHE_DIR = os.path.join(ROOT, 'cache', 'frames')
PRED_JSON = os.path.join(ROOT, 'cache', 'predictions.json')

app = Flask(__name__)
app.secret_key = 'deepfake-demo-2026'

# ── Load cache (once at startup) ────────────────────────────────────────────

print("Loading cache...", end=' ', flush=True)
_cache     = json.load(open(PRED_JSON))
_videos    = _cache['videos']          # {video_id: {label, model_guess, p_fake}}
_threshold = _cache['threshold']
ALL_VIDEO_IDS = sorted(_videos.keys())
print(f"done. {len(ALL_VIDEO_IDS)} videos, threshold = {_threshold:.3f}")


# ── Routes ──────────────────────────────────────────────────────────────────

@app.route('/')
def index():
    session.clear()
    # Bias model-correct videos toward the front using overlapping random ranges
    # Bias model-correct videos toward the front using overlapping random ranges.
    # Sort descending so pop() (which takes from the back) serves correct ones first.
    queue = sorted(
        ALL_VIDEO_IDS,
        key=lambda v: random.uniform(0, 0.65)
                      if _videos[v]['label'] == _videos[v]['model_guess']
                      else random.uniform(0.35, 1.0),
        reverse=True
    )
    session['queue']       = queue
    session['human_score'] = 0
    session['model_score'] = 0
    session['round']       = 0
    return render_template('index.html')


@app.route('/api/next')
def api_next():
    queue = session.get('queue', [])
    if not queue:
        return jsonify({'done': True})

    video_id = queue.pop()
    session['queue'] = queue
    session['round'] = session.get('round', 0) + 1

    entry = _videos[video_id]
    session['truth']       = entry['label']
    session['model_guess'] = entry['model_guess']
    session['p_fake']      = entry['p_fake']
    session['current_video'] = video_id

    return jsonify({
        'done':        False,
        'video_id':    video_id,
        'round':       session['round'],
        'human_score': session['human_score'],
        'model_score': session['model_score'],
    })


@app.route('/api/frame/<video_id>')
def api_frame(video_id):
    if video_id not in _videos:
        return 'Not found', 404
    return send_from_directory(CACHE_DIR, f'{video_id}.jpg', mimetype='image/jpeg')


@app.route('/api/guess/<int:human_guess>')
def api_guess(human_guess):
    truth       = session.get('truth')
    model_guess = session.get('model_guess')
    p_fake      = session.get('p_fake', 0.0)
    video_id    = session.get('current_video', '')

    if truth is None:
        return jsonify({'error': 'No active round'}), 400

    human_correct = int(human_guess == truth)
    model_correct = int(model_guess == truth)

    if human_correct:
        session['human_score'] = session.get('human_score', 0) + 1
    if model_correct:
        session['model_score'] = session.get('model_score', 0) + 1

    session.pop('truth', None)

    return jsonify({
        'truth':         truth,
        'model_guess':   model_guess,
        'p_fake':        p_fake,
        'human_correct': human_correct,
        'model_correct': model_correct,
        'human_score':   session['human_score'],
        'model_score':   session['model_score'],
        'video_id':      video_id,
    })


if __name__ == '__main__':
    port = int(sys.argv[1]) if len(sys.argv) > 1 else 5050
    print(f"Starting demo server on http://127.0.0.1:{port}")
    app.run(debug=False, port=port)
